tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "adr-tools"
brew "aria2"
brew "artillery"
brew "awscli"
brew "awslogs"
brew "bash-completion"
brew "clang-format"
brew "clockify"
brew "cmake"
brew "ctags"
brew "curl"
brew "derailed/k9s/k9s"
brew "diff-so-fancy"
brew "dive"
brew "dockutil"
brew "duti"
brew "exiftool"
brew "ffmpeg"
brew "flac"
brew "fzf"
brew "gcc"
brew "gh"
brew "ghostscript"
brew "gist"
brew "git"
brew "git-crypt"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "gource" # Git Video
brew "hashicorp/tap/packer"
brew "helm"
brew "htop"
brew "icdiff"
brew "id3v2"
brew "imagemagick" # SVGify
brew "jq"
brew "k3d"
brew "ksync"
brew "kubectx"
brew "kubernetes-cli"
brew "lame"
brew "lazygit"
brew "lftp" # Advanced FTP
brew "libav" # Git Video
brew "lsd"
brew "lzip"
brew "mas"
brew "minikube"
brew "mycli" # SQL Terminal Client
brew "neofetch"
brew "nmap"
brew "node"
brew "node-gyp"
brew "npm"
brew "nvm"
brew "openconnect"
brew "openssl@1.1"
brew "openvpn"
brew "pandoc"
brew "pdfgrep"
brew "perl"
brew "pkg-config" # Required by pdfgrep etc.
brew "potrace" # SVGify
brew "prettyping"
brew "pv"
brew "python3"
brew "reattach-to-user-namespace"
brew "ruby"
brew "rust"
brew "sloccount"
brew "socat"
brew "sox"
brew "stats"
brew "stow"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "websocat"
brew "wget"
brew "xsv"
brew "xz" # Required by many tools
brew "zsh"

cask "aldente"
cask "apparency"
cask "arc"
cask "audio-hijack"
cask "blackhole-2ch"
cask "brave-browser"
cask "daisydisk"
cask "docker"
cask "electrum"
cask "fission"
cask "font-hack-nerd-font"
cask "google-drive"
cask "gpg-suite"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "keeweb"
cask "keka"
cask "macfuse"
cask "mactex-no-gui"
cask "microsoft-edge"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "mixed-in-key"
cask "mp3tag"
cask "pop"
cask "postico"
cask "proxyman"
cask "rapidapi"
cask "raycast"
cask "rekordbox"
cask "spotify"
cask "tunnelblick"
cask "utm"
cask "vcv-rack"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
cask "xquartz"

# Mac App Store
mas "Affinity Photo", id: 824183456
mas "Shazam", id: 897118787
mas "WireGuard", id: 1451685025
mas "Yubico Authenticator", id: 1497506650
