tap 'buo/cask-upgrade'
tap 'caskroom/versions'
tap 'cloudfoundry/tap' # cf-cli
tap 'homebrew/cask-fonts'
tap 'wagoodman/dive' # dive

# Binaries
brew 'adr-tools'
brew 'aria2'
brew 'asciinema'
brew 'atool'
brew 'awscli'
brew 'awslogs'
brew 'bash-completion'
brew 'cf-cli' # CloudFoundry
brew 'clang-format'
brew 'clisp'
brew 'clojure'
brew 'cmake'
brew 'ctags'
brew 'diff-so-fancy'
brew 'dive'
brew 'dockutil'
brew 'duti'
brew 'emacs'
brew 'emojify'
brew 'exiftool'
brew 'ffmpeg'
brew 'fzf'
brew 'gcc'
brew 'gist'
brew 'git'
brew 'git-crypt'
brew 'gnupg'
brew 'golang'
brew 'gource' # Git Video
brew 'gpg-agent'
brew 'graphviz'
brew 'gs' # Ghostscript
brew 'heroku'
brew 'htop'
brew 'httpie'
brew 'icdiff'
brew 'imagemagick' # SVGify
brew 'jq'
brew 'kubectl'
brew 'lame'
brew 'lftp' # Advanced FTP
brew 'libav' # Git Video
brew 'lsd'
brew 'maven'
brew 'mono'
brew 'mpv'
brew 'mycli'
brew 'nmap'
brew 'npm'
brew 'openconnect'
brew 'openvpn'
brew 'p7zip' # 7zip
brew 'pdfgrep'
brew 'potrace' # SVGify
brew 'prettyping'
brew 'progress'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'sloccount'
brew 'socat'
brew 'sshrc'
brew 'stow'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'zsh'

# Apps
cask 'adobe-acrobat-reader'
cask 'alfred'
cask 'android-platform-tools'
cask 'daisydisk'
cask 'docker'
cask 'filezilla'
cask 'firefox'
cask 'font-hack-nerd-font'
cask 'google-backup-and-sync'
cask 'gpg-suite'
cask 'harvest'
cask 'inkscape'
cask 'intellij-idea'
cask 'iterm2'
cask 'java'
cask 'java-jdk-javadoc'
cask 'karabiner-elements'
cask 'keka'
cask 'libreoffice'
cask 'microsoft-office'
cask 'paw'
cask 'slack'
cask 'teamviewer'
cask 'tunnelblick'
cask 'typora'
cask 'virtualbox'
cask 'vlc'
cask 'wireshark'
cask 'xquartz'

# Mac App Store
mas 'Affinity Photo', id: 824183456
