#!/bin/bash

echo "Restoring dotfiles..."
while read line
do
    echo "Restore ${line}.bak to $(readlink ${line})"
	/bin/cp -Rf ${line}.bak $(readlink ${line})
done < <(find . -name "*" -and -not -path "*.git*" -type l)
echo "Done."
