#!/bin/bash

DIR=$(dirname "$0")

rm -rf ~/.bash_profile.bak
mv ~/.bash_profile ~/.bash_profile.bak

rm -rf ~/.sdkman/etc/config.bak
mv ~/.sdkman/etc/config ~/.sdkman/etc/config.bak

rm -rf ~/.zshrc.bak
mv ~/.zshrc ~/.zshrc.bak

stow -d "${DIR}" -t "${HOME}" bash
stow -d "${DIR}" -t "${HOME}" emacs
stow -d "${DIR}" -t "${HOME}" git
stow -d "${DIR}" -t "${HOME}" gpg
stow -d "${DIR}" -t "${HOME}" karabiner
stow -d "${DIR}" -t "${HOME}" kerberos
stow -d "${DIR}" -t "${HOME}" lftp
stow -d "${DIR}" -t "${HOME}" maven
stow -d "${DIR}" -t "${HOME}" powershell
stow -d "${DIR}" -t "${HOME}" sdkman
stow -d "${DIR}" -t "${HOME}" ssh
stow -d "${DIR}" -t "${HOME}" sshrc
stow -d "${DIR}" -t "${HOME}" subversion
stow -d "${DIR}" -t "${HOME}" tmux
stow -d "${DIR}" -t "${HOME}" vim
stow -d "${DIR}" -t "${HOME}" zsh
stow -d "${DIR}" -t "${HOME}/.zprezto/modules/prompt/functions/" zsh_theme
stow -d "${DIR}" -t "${VS_CODE_DIR}" vscode
