#!/bin/bash

echo "Writing data from symlink to file..."
while read line
do
    echo "Writing ${line} to ${line}.bak"
    cat ${line} > ${line}.bak
done < <(find . -name "*" -and -not -path "*.git*" -type l)
echo "Done."
