Set-Alias -Name bkems -Value Backup-EmsCache
Set-Alias -Name e -Value Exit-Session
Set-Alias -Name gui -Value Start-InGUI
Set-Alias -Name ll -Value Get-LongListing
Set-Alias -Name mac -Value Navigate-MacHome
Set-Alias -Name psm -Value Navigate-PowerShellModules
Set-Alias -Name rp1 -Value Reload-Profile
Set-Alias -Name rr -Value Remove-ReadOnly
Set-Alias -Name rsems -Value Restore-EmsCache
Set-Alias -Name vpn -Value Connect-LeonardoVPN
Set-Alias -Name wh -Value Connect-Devhost-VM
Set-Alias -Name whost -Value Connect-Devhost-VM
Set-Alias -Name wl -Value Connect-Parallels-VM
Set-Alias -Name wlocal -Value Connect-Parallels-VM