name: test

on:
  push:
    branches: [master]
    paths: ["bin/**"]
  pull_request:
    branches: [master]
    paths: ["bin/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pytest
      - run: python -m pytest bin/tests/ -v
